In [3]:
import pickle as pkl
from numpy import __version__ as numpyver
from pandas import __version__ as pandasver
print(numpyver, pandasver)

1.23.0 1.4.0

In [6]:
with open('df_neims_gecko_3_9_22.pkl', 'rb') as file:
    data = pkl.load(file)
data

,SMILES,spec
0,C=O,"[[14, 202], [15, 313], [16, 165], [18, 16], [1..."
1,O=C[N+](=O)[O-],"[[14, 72], [16, 151], [17, 70], [18, 108], [19..."
2,O=CC(=O)[N+](=O)[O-],"[[14, 153], [15, 174], [16, 125], [17, 36], [1..."
3,O=C(O)C(=O)[N+](=O)[O-],"[[14, 120], [15, 236], [16, 149], [17, 78], [1..."
4,O=C(OO)C(=O)[N+](=O)[O-],"[[14, 136], [15, 268], [16, 152], [17, 62], [1..."
...,...,...
166153,CC1(O)C(C(O)C(=O)OO[N+](=O)[O-])OOC1(O)C(=O)OO...,"[[14, 70], [15, 145], [16, 82], [17, 31], [18,..."
166154,CC1(O)C(C(O)C=O)OOC1(O)C(=O)OO[N+](=O)[O-],"[[14, 53], [15, 108], [16, 44], [17, 39], [18,..."
166155,CC1(O)C(C(=O)C=O)OOC1(O)C(=O)OO[N+](=O)[O-],"[[14, 54], [15, 123], [16, 54], [17, 45], [18,..."
166156,CC1(O)C(C(=O)OO[N+](=O)[O-])OOC1(O)C(=O)OO[N+]...,"[[14, 60], [15, 69], [16, 69], [26, 44], [27, ..."
166157,CC1(O)C(C(C=O)OO)OOC1(O)C(=O)OO,"[[14, 47], [15, 118], [16, 42], [17, 75], [18,..."

In [4]:
with open('df_neims_gecko_TMS_3_9_22.pkl', 'rb') as file:
    data = pkl.load(file)
data

,SMILES,spec
0,C=O,"[[14, 202], [15, 313], [16, 165], [18, 16], [1..."
1,O=C[N+](=O)[O-],"[[14, 72], [16, 151], [17, 70], [18, 108], [19..."
2,O=CC(=O)[N+](=O)[O-],"[[14, 153], [15, 174], [16, 125], [17, 36], [1..."
3,C[Si](C)(C)OC(=O)C(=O)[N+](=O)[O-],"[[14, 45], [15, 86], [16, 6], [18, 13], [25, 2..."
4,C[Si](C)(C)OOC(=O)C(=O)[N+](=O)[O-],"[[14, 67], [15, 193], [16, 20], [25, 27], [26,..."
...,...,...
166429,CC1(O[Si](C)(C)C)C(C(O[Si](C)(C)C)C(=O)OO[N+](...,"[[14, 5], [15, 17], [16, 0], [26, 3], [27, 49]..."
166430,CC1(O[Si](C)(C)C)C(C(C=O)O[Si](C)(C)C)OOC1(O[S...,"[[2, 3], [8, 0], [14, 15], [15, 30], [18, 21],..."
166431,CC1(O[Si](C)(C)C)C(C(=O)C=O)OOC1(O[Si](C)(C)C)...,"[[14, 18], [15, 44], [16, 1], [18, 1], [20, 5]..."
166432,CC1(O[Si](C)(C)C)C(C(=O)OO[N+](=O)[O-])OOC1(O[...,"[[14, 0], [15, 27], [26, 21], [27, 30], [28, 6..."
166433,CC1(O[Si](C)(C)C)C(C(C=O)OO[Si](C)(C)C)OOC1(O[...,"[[30, 3], [31, 14], [39, 5], [41, 30], [43, 35..."